#############
[application]
#############

#########
[web.app]
#########

# HTML title tag content
title = "cognitive"


##############
[web.resource]
##############
# It includes `assets` in web platform.

# Additional CSS style files.
style = []

# Additional JavaScript files
script = []

##################
[web.resource.dev]
##################

# Javascript code file
# serve: [dev-server] only
script = []

