#########
[package]
#########

name = "shlib"
description = "library that is shared between back-end and front-end sides"
version = "0.1.0"
edition = "2024"

##############
[dependencies]
##############

anyhow = { version = "1.0.100" }
thiserror = { version = "2.0.17" }
